# Generated by Django 4.1.5 on 2024-10-01 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('Id_no', models.CharField(max_length=100)),
                ('Serial_no', models.CharField(max_length=50)),
                ('Problem_description', models.Field(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Records',
            },
        ),
    ]
