# Generated by Django 4.1.5 on 2024-10-03 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_product_record_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='name',
            field=models.CharField(default=1, max_length=50),
        ),
    ]
