# Generated by Django 4.1.5 on 2024-10-03 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_record_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='name',
        ),
    ]
