# Generated by Django 4.1.5 on 2024-10-03 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_remove_record_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='Id_no',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
