# Generated by Django 4.1.5 on 2024-10-03 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0007_customer_remove_record_id_no_remove_record_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='customer',
        ),
        migrations.AddField(
            model_name='record',
            name='Id_no',
            field=models.CharField(default=1, max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name='record',
            name='email',
            field=models.CharField(default=1, max_length=100),
        ),
        migrations.AddField(
            model_name='record',
            name='first_name',
            field=models.CharField(default=1, max_length=50),
        ),
        migrations.AddField(
            model_name='record',
            name='last_name',
            field=models.CharField(default=1, max_length=50),
        ),
        migrations.AddField(
            model_name='record',
            name='phone',
            field=models.CharField(default=1, max_length=15),
        ),
        migrations.AlterField(
            model_name='record',
            name='Serial_no',
            field=models.CharField(default=1, max_length=50),
        ),
    ]
