# Generated by Django 4.1.5 on 2024-10-03 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0008_remove_record_customer_record_id_no_record_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='Id_no',
        ),
        migrations.RemoveField(
            model_name='record',
            name='email',
        ),
        migrations.RemoveField(
            model_name='record',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='record',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='record',
            name='phone',
        ),
        migrations.AddField(
            model_name='record',
            name='customer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='project.customer'),
        ),
        migrations.AlterField(
            model_name='record',
            name='Serial_no',
            field=models.CharField(max_length=50),
        ),
    ]
